# Generated by Django 3.0.5 on 2023-10-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('exam', '0003_teacherstudentinvolvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
            preserve_default=False,
        ),
    ]
